name: Run Python Tests
on: [push, pull_request]

jobs:
  test:
    runs-on: nvidia-cuda
    strategy:
      matrix:
        python-version: ["3.8", "3.10", "3.12"]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Check for GPU
      run: |
        echo "Checking for NVIDIA GPU..."
        nvidia-smi

    - name: Install dependencies with CUDA
      run: |
        python -m pip install --upgrade pip
        pip install .[dev,cuda12]

    - name: Run tests
      run: |
        pytest
